import { Transaction } from './types';

export const EXPENSE_CATEGORIES: string[] = [
  '🏠 Room Rent (রুম ভাড়া)',
  '🛒 Bajar (বাজার)',
  '🔥 Gas Bill (গ্যাস বিল)',
  '🚗 Travel (যাতায়াত)',
  '📶 WiFi (ওয়াইফাই)',
  '⚡ Electricity (বিদ্যুৎ)',
  '👨‍👩‍👦 Relatives (আত্মীয়-স্বজন)',
  '💊 Medicines (ঔষধ)',
  '🛏️ Room Accessories (রুমের জিনিসপত্র)',
  '🏡 Family Cost (ফ্যামিলি খরচ)',
  '❤ Mr & Mrs (ব্যক্তিগত/দম্পতি)',
  '🌙 Eid Cost (ঈদ খরচ)',
  '🐦 Pakhi (পাখি)',
  '💼 Official (অফিসিয়াল)',
  '🍎 Fruits (ফলমূল)',
  '💸 Loan Given (ধার দেওয়া)',
  '☕ Ghoraghuri/Adda (ঘোরাঘুরি/আড্ডা)',
  '🤝 Loan Repaid (ধার শোধ)',
  '👤 Personal (পার্সোনাল)',
  '🛍️ Shopping (শপিং)',
  '🍲 Food (খাবার)',
  '🏡 Home (বাসার খরচ)',
  '🏷️ Others (অন্যান্য)',
];

export const INCOME_CATEGORIES: string[] = [
  '💰 Salary (বেতন)',
  '📈 Arrear (বকেয়া)',
  '🤝 Borrowed Money (ধার নেওয়া)',
  '💵 Loan Repayment (ঋণ পরিষদ পাওয়া)',
  '📱 Bkash Load (বিকাশ লোড)',
  '🎁 Bonus (বোনাস)',
  '💻 Freelancing (ফ্রিল্যান্সিং)',
  '🏷️ Other Income (অন্যান্য)',
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-init-1',
    datetime: '10/1/2026, 10:00:00 AM',
    type: 'Income',
    category: '💰 Salary (বেতন)',
    date: '2026-10-01',
    value: 45000,
    note: 'October Monthly Salary',
  },
  {
    id: 'tx-init-2',
    datetime: '10/2/2026, 11:30:00 AM',
    type: 'Expense',
    category: '🏠 Room Rent (রুম ভাড়া)',
    date: '2026-10-02',
    value: 12000,
    note: 'House rent with service charge',
  },
  {
    id: 'tx-init-3',
    datetime: '10/3/2026, 04:15:00 PM',
    type: 'Expense',
    category: '🛒 Bajar (বাজার)',
    date: '2026-10-03',
    value: 2350,
    note: 'Weekly grocery shopping',
  },
  {
    id: 'tx-init-4',
    datetime: '10/4/2026, 02:00:00 PM',
    type: 'Expense',
    category: '⚡ Electricity (বিদ্যুৎ)',
    date: '2026-10-04',
    value: 1450,
    note: 'Electricity meter bill',
  },
  {
    id: 'tx-init-5',
    datetime: '10/5/2026, 07:45:00 PM',
    type: 'Expense',
    category: '🚗 Travel (যাতায়াত)',
    date: '2026-10-05',
    value: 380,
    note: 'Metro & Rickshaw fare',
  },
  {
    id: 'tx-init-6',
    datetime: '10/6/2026, 09:20:00 PM',
    type: 'Expense',
    category: '🍲 Food (খাবার)',
    date: '2026-10-06',
    value: 620,
    note: 'Dinner with colleagues',
  },
  {
    id: 'tx-init-7',
    datetime: '10/7/2026, 06:10:00 PM',
    type: 'Expense',
    category: '🍎 Fruits (ফলমূল)',
    date: '2026-10-07',
    value: 450,
    note: 'Apples and bananas',
  },
  {
    id: 'tx-init-8',
    datetime: '10/8/2026, 11:00:00 AM',
    type: 'Income',
    category: '💻 Freelancing (ফ্রিল্যান্সিং)',
    date: '2026-10-08',
    value: 8500,
    note: 'Website UI bug fix bonus',
  },
];

export const GOOGLE_SCRIPT_URL =
  'https://script.google.com/macros/s/AKfycbwdR3oDJiUFWFopvUeLI-8r92-9uS-jRUdRKFW3CghmmIy84sQZjNEeEkY6yboG8g4z/exec';
